# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/build

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn integration-test
      
      
      - run: |
            if [[ "$CIRCLE_BRANCH" = "master" ]]
            then
               git config --global user.email "pratikghodekar@gmail.com"
               git config --global user.name "pratikghodekar" 
               mvn -B release:prepare release:perform
            fi

  deploy:
    working_directory: ~/deploy
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      - checkout
    
      - run:
          name: Clone git repo
          command: |            
            git clone git@github.com:pratik-ansible/backend-server.git
            
 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
           requires:
              - build
